repos:
    - repo: https://github.com/python-poetry/poetry
      rev: 1.7.1
      hooks:
          - id: poetry-check
          - id: poetry-lock
          - id: poetry-export
            args: ["-f", "requirements.txt", "--output", "requirements.txt"]
          - id: poetry-export
            args:
                [
                    "-f",
                    "requirements.txt",
                    "--only",
                    "test",
                    "--output",
                    "requirements-test.txt",
                ]
          - id: poetry-export
            args:
                [
                    "-f",
                    "requirements.txt",
                    "--only",
                    "dev",
                    "--output",
                    "requirements-dev.txt",
                ]
          - id: poetry-export
            args:
                [
                    "-f",
                    "requirements.txt",
                    "--only",
                    "docs",
                    "--output",
                    "./docs/requirements.txt",
                ]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/psf/black
      rev: 24.2.0
      hooks:
          - id: black
            args: ["src/"]
